name: Rust Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  cli-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Grant executive permissions to script
        run: chmod +x ./crates/vach-cli/test_data/test.sh
      - name: Run CLI tests
        run: cd ./crates/vach-cli/test_data/ && ./test.sh
