name: Rust Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  single-threaded-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Build Archives
        run: cargo test -p vach --features default --features crypto --features compression -- tests::builder_no_signature tests::builder_with_signature tests::builder_with_encryption --nocapture
      - name: Test Against Archives
        run: cargo test -p vach --features default --features crypto --features compression -- --skip builder_ --nocapture
        env:
          RUST_LOG: trace
  multithreaded-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Build Archives
        run: cargo test -p vach --features all -- tests::builder_no_signature tests::builder_with_signature tests::builder_with_encryption --nocapture
      - name: Test Against Archives
        run: cargo test -p vach --features all -- --skip builder_ --nocapture
        env:
          RUST_LOG: trace
